### ISSUE TITLE
mvn clean package issue + project installation question

### ISSUE THREAD

**Issue by sambk17** [openapi-json-schema-tools/openapi-json-schema-generator#218]
##### Description

I previously use openapi-generator until [v7.0.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v7.0.0) [decommissioned the python client generator](https://github.com/OpenAPITools/openapi-generator/pull/15486)

I am new to opeanpi-json-schema-generator (previously used openapi-generator) and attempted the following to install based on the README:

###### [Getting Started](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator#getting-started) 

I used:
```
git clone https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
cd openapi-json-schema-generator
mvn clean package
```

This resulted in the following error:
```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   URLPathUtilsTest.testGetServerURLWithVariables:115 expected [https://{user}.example.com/v1] but found [http://localhost]
[INFO]
[ERROR] Tests run: 463, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.743 s
[INFO] Finished at: 2023-08-25T16:20:21-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project openapi-json-schema-generator-cli: There are test failures.
[ERROR]
[ERROR] Please refer to /{local_pathway}/openapi-json-schema-generator/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

###### Install Jar directly from maven.org

Within the README, "You can also download the JAR (latest release) directly from [maven.org](https://repo1.maven.org/maven2/org/openapijsonschematools/openapi-json-schema-generator-cli/6.1.0/openapi-json-schema-generator-cli-6.1.0.jar)"

⬆️ This link above does not exist (404) ⬆️ .  In maven.org, I could not search for `openapi-json-schema-generator-cli`.  Does this exist?

##### openapi-generator version

[v3.0.0](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/releases/tag/3.0.0)

##### OpenAPI declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

* Will a v3.0.0 of the JAR be uploaded to maven.org?

**Comment by spacether** [comment]
At this time I do not plan on publishing to maven. If more users desire it, I can add it. Can you use the docker images?
what is your operating system and architecture?
what is your Java version?
what is your mvn version?

I need this info to reproduce the bug.

**Comment by sambk17** [comment]
1. Can you use the docker images? I will set up Docker to test after I have changed my workflows over from openapi-generator to openapi-json-schema-generator.  I'll post here if I run into issues.
2. What is your operating system and architecture? My workflow uses `ubuntu-latest`.  The architecture so far only consists of A) generating the Python SDK Client from an openapi.yaml and B) Using [Prism](https://github.com/stoplightio/prism) to Mock a Server to perform unit tests
3. What is your Java version? 11.0.20
4. What is your mvn version? 3.8.8

**Comment by sambk17** [comment]
> At this time I do not plan on publishing to maven. If more users desire it, I can add it.
> 
> Some questions for you:
> 
> 1. Can you use the docker images?
> 2. What is your operating system and architecture?
> 3. What is your Java version?
> 4. What is your mvn version?
> 
> I need this info to reproduce the bug as all tests are currently passing locally and in CI

Can you use the docker images? I will set up Docker to test after I have changed my workflows over from openapi-generator to openapi-json-schema-generator. I'll post here if I run into issues.
What is your operating system and architecture? My GitHub workflow uses ubuntu-latest. The architecture so far only consists of A) generating the Python SDK Client from the openapi.yaml and B) Using [Prism](https://github.com/stoplightio/prism) to Mock a Server to perform unit tests. That's it (so far) 😄
What is your Java version? 11.0.20
What is your mvn version? 3.8.8

**Comment by spacether** [comment]
Hmm I wonder if this is a Java 19 issue. We are both on Mac oses.

**Comment by spacether** [comment]
@sambk17 does it work if you use Java 11?

**Comment by sambk17** [comment]
Hi @spacether 👋 - I changed out the Java version (11.0.19) and it worked!!

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.690 s
[INFO] Finished at: 2023-08-28T08:45:53-07:00
[INFO] ------------------------------------------------------------------------
```

Any chance is there an explanation for the difference in Java version? 😄

**Comment by spacether** [comment]
Glad to hear it. Not sure why one would have this bug and the other wouldn't. I changed from Java 8 to Java 11 because 11 is the oldest active long term support (LTS) release. The next LTS release after 11 is 17.

**Comment by sambk17** [comment]
Update: I have also tested this within an `ubuntu-latest` GitHub Actions Workflow using Java 11 and it also works as expected.  

@spacether - Thanks again for helping clarify things.  I will mark this as Closed.
