### ISSUE TITLE
pip install & import library issue

### ISSUE THREAD

**Issue by sambk17** [openapi-json-schema-tools/openapi-json-schema-generator#225]
##### Description

Prior to using openapi-json-schema-generator (v3.0.0), I was using openapi-generator (v6.6.0).  With openapi-generator, I was able to both pip install and import the package (repo) locally.  For openapi-json-schema-generator, I am encountering an issue with both pip install and import

##### openapi-json-schema-generator version

v3.0.0

##### OpenAPI declaration file content or url

There is a openapi.yaml file (I can provide any details if required) at the root level.  Nothing fancy with this file.

##### Command line used for generation

[BEFORE] Using openapi-generator:
```
openapi-generator-cli generate \
  -g python \
  -i openapi.yaml \
  -o . \
  --package-name mlp
```

Directory output (at the root):
<img width="271" alt="image" src="https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/assets/10478566/de0f72ef-03e9-40d4-a6c9-4e87b2260fb3">

[CURRENT] Using openapi-json-schema-generator:
```
java -jar openapi-json-schema-generator-cli.jar generate \
  -g python \
  -i openapi.yaml \
  -o . \
  --package-name mlp
```
Directory output (at the root):
<img width="271" alt="image" src="https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/assets/10478566/4af58305-c905-4010-80ca-73091f2698d1">

##### Steps to reproduce

When I perform `pip install https://github.com/{repo_name}`, I get the following error:
```
ERROR: HTTP error 404 while getting https://github.com/{repo_name}
ERROR: Could not install requirement https://github.com/{repo_name} because of HTTP error 404 Client Error: Not Found for url: https://github.com/{repo_name} for URL https://github.com/{repo_name}
```

When I perform `import mlp` (from the `src/` directory) within a Jupyter Notebook, I get:
```
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Generic, immutabledict
```

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

Is the current process that I will need to manually create a setup.py file at the root?  And/or do I need to modify anything else in order to be able to `import mlp`?

**Comment by spacether** [comment]
So it looks like you are missing the pyproject.tml file.
I am unable to reproduce your issue. I ran:
```
docker run --rm -v "${PWD}:/local" openapijsonschematools/openapi-json-schema-generator-cli:3.0.0 generate \
    -i /local/openapi.yaml \
    -g python \
    -o /local/out/python --package-name mlp
```
And in the /local/out/python folder I have these files:
```
README.md				migration_2_0_0.md			pyproject.toml				test-requirements.txt
docs					migration_3_0_0.md			src					tox.ini
git_push.sh				migration_other_python_generators.md	test
```
Which includes the needed pyproject.toml

Please:
- verify the commit hash of the 3.0.0 version that you are using
- show the results of running `java -jar openapi-json-schema-generator-cli.jar version`
- please paste in the contents of your generated root directory using ls like I did

**Comment by spacether** [comment]
That looks fine. I think that you were just ignoring the critical toml file

**Comment by sambk17** [comment]
Thanks @spacether for the feedback!  I added the pyproject.toml file and I am able to use `python -m pip install .` to successfully install the package.  For that reason, I will close out this Issue.

Note: I will raise a separate issue shortly in regards to having problems with `immutabledict`.

**Comment by spacether** [comment]
Labeling this issue as invalid because with default options pip installation works, installation failed in this case because the author explicitly omitted the critical pyproject.toml file which is a critical file needed for package installation
