### ISSUE TITLE
Templating - import with a prefix issue in various handlebar files

### ISSUE THREAD

**Issue by sambk17** [openapi-json-schema-tools/openapi-json-schema-generator#236]
###### Background Info
* I am generating the SDK client as a subpackage (not a package)
  * e.g. root directory of the repo is `mlp` and the generated code is under `mlp/gen/`
* Because this is a subpackage, I used `author template` to get all the handlebar files.  I then modified any .hbs files with `from {{packageName}}...` or `import {{packageName}}...` and added them to a template folder (`mlp/gen_templates/`)
* Essentially the handlebar changes I made:
  * e.g. `from {{packageName}}...` -> `from mlp.gen.src.{{packageName}}...`

###### Handlebar Issues
* After generating the SDK client, there are various scripts in the `src/paths/` directory with the missing prefix (`mlp.gen.src.`) in the import statements
* These are the the following handlebar scripts added (emphasis on `paths/` as that's the issue):
![image](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/assets/10478566/4e40995b-72d3-418e-be77-c0086af04247)
* These are the following paths files which are not generating properly with the prefix (`mlp.gen.src.`):
  1. `/paths/*/request_body/content/application_json/schema.py`
  2. `paths/*/post/operation.py`
  3. `paths/*/put/parameters/parameter_0/__init__.py`
  4. `paths/*/put/path_parameters.py`

##### openapi-generator version

v3.0.0

###### Command used to download handlebar files:
```
java -jar openapi-json-schema-generator-cli.jar author template -g python
```

###### Command used to generate the SDK:
```
java -jar openapi-json-schema-generator-cli.jar generate \
    -i mlp/openapi.yaml \
    -g python \
    -o mlp/gen \
    -t mlp/gen_templates 
```

##### Suggest a fix/enhancement

After using `author template` to get all handlebar files, I can't find the handlebar script(s) associated with the 4 `paths/` patterns described above.  

Do I need to create new handlebar files for `gen_templates/paths/`?  Otherwise is there a better approach to tackling this problem?

**Comment by spacether** [comment]
Have you considered including the prefitin packageName? Why is packageName not set in your invocation?

**Comment by sambk17** [comment]
@spacether - Very good idea!  I'll test this out today and report back here 😄

**Comment by sambk17** [comment]
If I add the prefix `mlp.gen.src` to package-name as such:
```
java -jar openapi-json-schema-generator-cli.jar generate \
      -i mlp/openapi.yaml \
      -g python \
      -o mlp/gen \
      --package-name mlp.gen.src.mlp_client
```

While this fixes the import statements in the generated scripts, the pathways now look like this:
<img width="258" alt="image" src="https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/assets/10478566/57358abb-0b01-4cc7-b755-e01411cd9b27">

**Comment by spacether** [comment]
How about using mlp.gen.mlp_client as the package name? Otherwise src will appear twice.
Also the init file will be missing from mlp.gen.mlp_client and possibly the src folder and it will need to be added there. It is easier to package the generated client as it's own package in its own repo, then have your mlp repo install and use it.

**Comment by sambk17** [comment]
@spacether - I tried `mlp.gen.mlp_client` as the packageName and that did not resolve the issue (`mlp/gen/src/mlp/gen/mlp_client/`).  I will package the generated client as its own package in its own repo then have mlp repo install and use it as a sub-package.  Thank you for the guidance 😄 👍

**Comment by spacether** [comment]
You're welcome. Thank you for your flexibility in considering other installation layouts
