### ISSUE TITLE
[REQ][python] Allow the body type to be `bytes` when the content-type is "application/octet-stream"

### ISSUE THREAD

**Issue by nponsard** [openapi-json-schema-tools/openapi-json-schema-generator#243]
### Is your feature request related to a problem? Please describe.

When an endpoint accepts the mime type "application/octet-stream", allow the body in the function parameters to be of type `bytes`. This would allow to send data without a text encoding. 

## Describe alternatives you've considered

Doing the request manually using `ApiClient.rest_client.request()` this is not optimal.

**Comment by spacether** [comment]
This is part of the current functionality
- see [this endpoint](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/src/test/resources/3_0/python/petstore_customized.yaml#L1393)
- [see these docs](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/samples/client/petstore/python/docs/paths/fake_upload_download_file/post.md), where bytes of a file may be input for body

How are you describing your request?

**Comment by nponsard** [comment]
Ah the schema I have doesn't specify a format. This seems to be my problem.
