### ISSUE TITLE
[REQ] Reduce the docker image size

### ISSUE THREAD

**Issue by spacether** [openapi-json-schema-tools/openapi-json-schema-generator#30]
### Is your feature request related to a problem? Please describe.

Reduce the docker image size
All of those files are not needed

**Comment by sann3** [comment]
@spacether Can you please update the unnecessary file list?

**Comment by spacether** [comment]
The Dockerfile that docker hub uses is:
https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/Dockerfile
And it copies over many folders into that image
Not all are needed

There is another dockerfile 
https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/modules/openapi-json-schema-generator-cli/Dockerfile

which may be able to be used instead
At a minimum because this repo is not running the online generation server, copying that over into the docker image is not needed

**Comment by batman1911** [comment]
Can you please assign this to me ?

**Comment by spacether** [comment]
@batman1911 any progress here?

**Comment by spacether** [comment]
Unassigning because no progress was made

**Comment by spacether** [comment]
Docker image will be reduced by this PR: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/189
