### ISSUE TITLE
[BUG][PYTHON] $ref to remote url is failing with v2.0.0 and higher

### ISSUE THREAD

**Issue by BaptisteSaves** [openapi-json-schema-tools/openapi-json-schema-generator#341]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you tested with the latest master to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request

##### Description

When using an http reference, the generator fails with error `[main] WARN org.openapijsonschematools.codegen.common.ModelUtils - Failed to get the schema at $ref: `

Is using an http $ref supported by the generator ?

Bonus point:
Some of our http ref have local reference `./XXX.yaml` that also needs to be followed.

##### openapi-json-schema-generator version

3.3.1

##### OpenAPI declaration file content or url

```yaml
$ref: https://XXX.yaml`
```

##### Generation Details
`docker run --rm -v ./:/local openapijsonschematools/openapi-json-schema-generator-cli:3.3.1 generate -i /local/my-service.yml -g python -o /local/out`

##### Steps to reproduce

Generate the client with a ref to an http yaml

##### Suggest a fix

The `getSimpleRef` seems to return null for any http $ref https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/d41a95e953d7379033f7dbe60c88df66bc4f4b9c/src/main/java/org/openapijsonschematools/codegen/common/ModelUtils.java#L324
And I haven't found any place where the referenced file would be downloaded.

**Comment by spacether** [comment]
This is happening because it is the parsers job to get remote refs and local file refs. I turned ref resolving off to preserve refs inside openapi documents from one place to another. This could be fixed by
- parsing the document twice
- once as it is now
- and the other time with resolve refs on
- then iterate through the first parsed schemas and any refs outside the document should be replaced with results from the second parsing


Is this something that you want to fix?

**Comment by BaptisteSaves** [comment]
Thanks for the quick answer :pray: 

> Is this something that you want to fix?

I tried to understand the code to see if there was a quick fix to do. So far I am struggling to understand how this work and I do not think I have the time or capacity to deliver a fix of this amplitude

**Comment by spacether** [comment]
Are you open to using redlocity cli to pre process your openapi document and bundle it into one output openapi document?

**Comment by BaptisteSaves** [comment]
It feels strange that this is not supported in v3 as we were using it in V1.0.4. 

Yes, it seems at first glance that using redocly-cli as a pre step could work for us

**Comment by BaptisteSaves** [comment]
@spacether Should we close this issue as not planned ?
